openapi: 3.0.3
info:
  title: SettleUp Games API
  description: 게임 정산 API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: 로컬 개발 서버

paths:
  /settlements/{settlementId}/rounds:
    get:
      summary: 게임 라운드 목록 조회
      tags: [GameRounds]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameRound'

    post:
      summary: 게임 라운드 추가
      tags: [GameRounds]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameRoundRequest'
      responses:
        '201':
          description: 추가됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameRound'
        '409':
          description: 라운드 번호 중복

  /settlements/{settlementId}/rounds/{roundId}:
    get:
      summary: 게임 라운드 상세 조회
      tags: [GameRounds]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: roundId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameRoundDetail'

    put:
      summary: 게임 라운드 수정
      tags: [GameRounds]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: roundId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGameRoundRequest'
      responses:
        '200':
          description: 수정됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameRound'

    delete:
      summary: 게임 라운드 삭제
      tags: [GameRounds]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: roundId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제됨

  /settlements/{settlementId}/rounds/{roundId}/results:
    post:
      summary: 게임 결과 추가/수정 (배치)
      tags: [GameResults]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: roundId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateGameResultRequest'
      responses:
        '200':
          description: 저장됨
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameResult'
        '400':
          description: 잘못된 요청 (참가자 중복, 금액 불일치 등)

components:
  schemas:
    GameRound:
      type: object
      required: [id, settlementId, roundNumber, multiplier, playedAt, createdAt]
      properties:
        id:
          type: string
          format: uuid
        settlementId:
          type: string
          format: uuid
        roundNumber:
          type: integer
          minimum: 1
        name:
          type: string
          maxLength: 100
          nullable: true
        baseAmount:
          type: number
          format: decimal
          minimum: 0
          nullable: true
        multiplier:
          type: number
          format: decimal
          minimum: 0
          default: 1.0
        playedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time

    GameRoundDetail:
      allOf:
        - $ref: '#/components/schemas/GameRound'
        - type: object
          properties:
            results:
              type: array
              items:
                $ref: '#/components/schemas/GameResult'

    GameResult:
      type: object
      required: [id, roundId, participantId, outcome, amount]
      properties:
        id:
          type: string
          format: uuid
        roundId:
          type: string
          format: uuid
        participantId:
          type: string
          format: uuid
        participantName:
          type: string
        outcome:
          type: string
          enum: [WIN, LOSE, DRAW]
        amount:
          type: number
          format: decimal
          description: WIN이면 양수, LOSE면 음수, DRAW면 0
        note:
          type: string
          maxLength: 200
          nullable: true

    CreateGameRoundRequest:
      type: object
      required: [roundNumber, playedAt]
      properties:
        roundNumber:
          type: integer
          minimum: 1
        name:
          type: string
          maxLength: 100
        baseAmount:
          type: number
          format: decimal
          minimum: 0
        multiplier:
          type: number
          format: decimal
          minimum: 0
          default: 1.0
        playedAt:
          type: string
          format: date-time
        results:
          type: array
          items:
            $ref: '#/components/schemas/CreateGameResultRequest'
          description: 라운드 생성 시 결과도 함께 추가 가능

    UpdateGameRoundRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        baseAmount:
          type: number
          format: decimal
          minimum: 0
        multiplier:
          type: number
          format: decimal
          minimum: 0
        playedAt:
          type: string
          format: date-time

    CreateGameResultRequest:
      type: object
      required: [participantId, outcome, amount]
      properties:
        participantId:
          type: string
          format: uuid
        outcome:
          type: string
          enum: [WIN, LOSE, DRAW]
        amount:
          type: number
          format: decimal
        note:
          type: string
          maxLength: 200

tags:
  - name: GameRounds
    description: 게임 라운드 관리
  - name: GameResults
    description: 게임 결과 관리
