openapi: 3.0.3
info:
  title: SettleUp Settlements API
  description: 정산 관리 API (여행 및 게임 정산)
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: 로컬 개발 서버
  - url: https://api.settleup.com/v1
    description: 프로덕션 서버

paths:
  /settlements:
    get:
      summary: 정산 목록 조회
      tags: [Settlements]
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [TRAVEL, GAME]
          description: 정산 유형 필터
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, COMPLETED, ARCHIVED]
          description: 상태 필터
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/SettlementSummary'
                  totalElements:
                    type: integer
                  totalPages:
                    type: integer
                  page:
                    type: integer
                  size:
                    type: integer

    post:
      summary: 새 정산 생성
      tags: [Settlements]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSettlementRequest'
      responses:
        '201':
          description: 생성됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settlement'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /settlements/{settlementId}:
    get:
      summary: 정산 상세 조회
      tags: [Settlements]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettlementDetail'
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: 정산 수정
      tags: [Settlements]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSettlementRequest'
      responses:
        '200':
          description: 수정됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settlement'
        '409':
          description: 버전 충돌
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: 정산 삭제
      tags: [Settlements]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제됨
        '404':
          description: 찾을 수 없음

  /settlements/{settlementId}/participants:
    get:
      summary: 참가자 목록 조회
      tags: [Participants]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participant'

    post:
      summary: 참가자 추가
      tags: [Participants]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateParticipantRequest'
      responses:
        '201':
          description: 추가됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Participant'
        '409':
          description: 이름 중복
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /settlements/{settlementId}/participants/{participantId}:
    put:
      summary: 참가자 수정
      tags: [Participants]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: participantId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateParticipantRequest'
      responses:
        '200':
          description: 수정됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Participant'

    delete:
      summary: 참가자 삭제 (비활성화)
      tags: [Participants]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: participantId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제됨
        '400':
          description: 관련 데이터 존재 (삭제 불가)

  /settlements/{settlementId}/calculate:
    post:
      summary: 정산 계산
      tags: [Settlements]
      description: 최종 정산 거래 목록 계산
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 계산 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculationResult'
        '400':
          description: 계산 불가 (데이터 부족)

  /settlements/{settlementId}/export:
    get:
      summary: 정산 내용 텍스트 내보내기
      tags: [Settlements]
      parameters:
        - name: settlementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: format
          in: query
          schema:
            type: string
            enum: [text, markdown, csv]
            default: text
      responses:
        '200':
          description: 텍스트 내보내기
          content:
            text/plain:
              schema:
                type: string
                example: |
                  제주도 여행 정산
                  기간: 2025-11-10 ~ 2025-11-12
                  참가자: 철수, 영희, 민수

                  [지출 내역]
                  1. 렌터카 - 150,000원 (철수 지불)
                     철수: 50,000원 / 영희: 50,000원 / 민수: 50,000원

                  [최종 정산]
                  민수 → 철수: 70,000원
                  민수 → 영희: 10,000원

components:
  schemas:
    SettlementSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        type:
          type: string
          enum: [TRAVEL, GAME]
        status:
          type: string
          enum: [ACTIVE, COMPLETED, ARCHIVED]
        participantCount:
          type: integer
        totalAmount:
          type: number
          format: decimal
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Settlement:
      type: object
      required: [id, title, type, status, creatorId, currency, createdAt, updatedAt, version]
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          minLength: 1
          maxLength: 100
        type:
          type: string
          enum: [TRAVEL, GAME]
        status:
          type: string
          enum: [ACTIVE, COMPLETED, ARCHIVED]
        creatorId:
          type: string
          format: uuid
        description:
          type: string
          maxLength: 500
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        currency:
          type: string
          default: KRW
          example: KRW
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        version:
          type: integer
        syncStatus:
          type: string
          enum: [PENDING, SYNCED, CONFLICT]

    SettlementDetail:
      allOf:
        - $ref: '#/components/schemas/Settlement'
        - type: object
          properties:
            participants:
              type: array
              items:
                $ref: '#/components/schemas/Participant'
            expenseCount:
              type: integer
            roundCount:
              type: integer

    CreateSettlementRequest:
      type: object
      required: [title, type]
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 100
        type:
          type: string
          enum: [TRAVEL, GAME]
        description:
          type: string
          maxLength: 500
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        currency:
          type: string
          default: KRW

    UpdateSettlementRequest:
      type: object
      required: [version]
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        status:
          type: string
          enum: [ACTIVE, COMPLETED, ARCHIVED]
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        version:
          type: integer
          description: 낙관적 잠금용 버전

    Participant:
      type: object
      required: [id, settlementId, name, isActive, joinedAt]
      properties:
        id:
          type: string
          format: uuid
        settlementId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
          nullable: true
        name:
          type: string
          minLength: 1
          maxLength: 50
        isActive:
          type: boolean
        joinedAt:
          type: string
          format: date-time

    CreateParticipantRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        userId:
          type: string
          format: uuid
          nullable: true

    UpdateParticipantRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        isActive:
          type: boolean

    CalculationResult:
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        balances:
          type: object
          additionalProperties:
            type: number
            format: decimal
          description: 참가자별 순 잔액 (participantId -> balance)

    Transaction:
      type: object
      required: [id, settlementId, fromParticipantId, toParticipantId, amount, status, createdAt]
      properties:
        id:
          type: string
          format: uuid
        settlementId:
          type: string
          format: uuid
        fromParticipantId:
          type: string
          format: uuid
        fromParticipantName:
          type: string
        toParticipantId:
          type: string
          format: uuid
        toParticipantName:
          type: string
        amount:
          type: number
          format: decimal
        status:
          type: string
          enum: [PENDING, COMPLETED, CANCELLED]
        completedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time

    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          example: VALIDATION_ERROR
        message:
          type: string
          example: 잘못된 요청입니다
        details:
          type: object
          additionalProperties: true

tags:
  - name: Settlements
    description: 정산 관리
  - name: Participants
    description: 참가자 관리
